### ISSUE TITLE
How do I change languages?

### ISSUE THREAD

**Issue by coldKingdom** [clusteramaryllis/laravel-gettext#1]
Hello!

I'm sorry for probably being stupid, but how do I change the language?

I have set the language to 'sv' in app.php, but it's still in English.
Trying to do a set_locale results in undefined function.

Thank you in advance!

**Comment by clusteramaryllis** [comment]
might want to ask you first, what version did you use of this package?

**Comment by coldKingdom** [comment]
Sorry, I use 1.1.0.

**Comment by clusteramaryllis** [comment]
Whoops, sorry. It should be fixed on 1.1.1

well if you change locale in `app.php`,
to change language you can use e.g.

``` php
set_locale(LC_ALL, \Config::get('app.locale'));
```

**Comment by coldKingdom** [comment]
It's alright :)

Seems to be working now, except that I don't get the Swedish language to be loaded.
I have translated all the strings and saved it, tried restarting Apache for caching issues. But no luck.

Any ideas? :)

**Comment by clusteramaryllis** [comment]
I tried some sample

1) create view on: `resources/views/test.blade.php`

``` html
{!! _('We have e-mailed your password reset link!') !!}
```

2) run `php artisan vendor:publish` to publish the config

3) add some locale in `config/gettext.php` in languages array

``` php
    'languages' => [
        'en' => [
            'locale' => 'en_US',
            'encoding' => 'utf-8',
            'plural_forms' => "nplurals=2; plural=(n != 1);",
        ],
        'sv' => [
            'locale' => 'sv_SE', // usually use IDLanguage_IDCountry format like suggested in phptal.org/manual/en/split/gettext.html
            'encoding' => 'utf-8',
            'plural_forms' => "nplurals=2; plural=(n != 1);",
        ],
    ],
```

4) run `php artisan gettext:create --sources="resources\views"`. This will generate .po files in

```
resources\locale\en_US\LC_MESSAGES\messages.po
resources\locale\sv_SE\LC_MESSAGES\messages.po
```

& scan files on resources/views directory.

5) I usually edit .po files using PoEdit (clicking update, start translating, and save). It will generate .mo file in the same place.

6) simple test in my route

``` php
Route::get('lang/{id}', function($id) {

    $lang = Config::get('gettext.languages.'.$id);

    set_locale(LC_ALL, $lang['locale'].'.'.$lang['encoding']); // e.g. sv_SE.utf-8
    bindtextdomain('messages', base_path('resources/locale')); // locate to correct path
    textdomain('messages'); // set default domain

    return view('test');
});
```

7)
![Test](http://i.imgur.com/1Po2OMi.jpg)
seems working

This test is on WINDOWS machine. Should be working on UNIX also since [Unit Test](https://github.com/clusteramaryllis/laravel-gettext/blob/master/tests/unit/GettextTest.php) passing on travis.

**Comment by coldKingdom** [comment]
Thank you very much!

I really appreciate your help. For a newbie like me, it's not really obvious to set bindtextdomain and textdomain, didn't even realize set_locale existed before I looked in your tests. :)

It would be nice to add these explanations to the readme file.

Good work!
